FROM node:8.12.0
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN apt-get --assume-yes update
RUN apt-get --assume-yes install vim
RUN npm install -g nodemon


EXPOSE 3000
CMD [ "npm", "start" ]