FROM node:8.12.0
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN apt-get --assume-yes update
RUN apt-get --assume-yes install vim
COPY package*.json ./
COPY . .

RUN npm install

EXPOSE 3000
CMD [ "npm", "start" ]
